version: '3.4'

services:

  db:
    image: mlflow:latest
    container_name: con_mlflow
    volumes: 
      - .:/home/project
    restart: always
    environment: 
      user: artinmajdi


  code:
    image: mlflow
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "5000:5000"
      - "6789:6789"
      - "22:22"
    
